name: Run Tests

on:
    push:
    pull_request:
    
jobs:
    unittests:
        name: Run unittests
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3 

            - name: Run test
              run: python -m unittest discover -s tests

